//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.30 at 11:14:26 PM CEST 
//


package dk.kea.si.movies.domain.wiki;

import javax.xml.bind.annotation.XmlRegistry;

import dk.kea.si.movies.domain.wiki.SearchSuggestion.Query;
import dk.kea.si.movies.domain.wiki.SearchSuggestion.Section;
import dk.kea.si.movies.domain.wiki.SearchSuggestion.Section.Item;
import dk.kea.si.movies.domain.wiki.SearchSuggestion.Section.Item.Description;
import dk.kea.si.movies.domain.wiki.SearchSuggestion.Section.Item.Image;
import dk.kea.si.movies.domain.wiki.SearchSuggestion.Section.Item.Text;
import dk.kea.si.movies.domain.wiki.SearchSuggestion.Section.Item.Url;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the dk.kea.si.movies.domain package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: dk.kea.si.movies.domain
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SearchSuggestion.Section.Item.Image }
     * 
     */
    public SearchSuggestion.Section.Item.Image createSearchSuggestionSectionItemImage() {
        return new SearchSuggestion.Section.Item.Image();
    }

    /**
     * Create an instance of {@link SearchSuggestion.Section.Item.Description }
     * 
     */
    public SearchSuggestion.Section.Item.Description createSearchSuggestionSectionItemDescription() {
        return new SearchSuggestion.Section.Item.Description();
    }

    /**
     * Create an instance of {@link SearchSuggestion.Query }
     * 
     */
    public SearchSuggestion.Query createSearchSuggestionQuery() {
        return new SearchSuggestion.Query();
    }

    /**
     * Create an instance of {@link SearchSuggestion }
     * 
     */
    public SearchSuggestion createSearchSuggestion() {
        return new SearchSuggestion();
    }

    /**
     * Create an instance of {@link SearchSuggestion.Section }
     * 
     */
    public SearchSuggestion.Section createSearchSuggestionSection() {
        return new SearchSuggestion.Section();
    }

    /**
     * Create an instance of {@link SearchSuggestion.Section.Item.Text }
     * 
     */
    public SearchSuggestion.Section.Item.Text createSearchSuggestionSectionItemText() {
        return new SearchSuggestion.Section.Item.Text();
    }

    /**
     * Create an instance of {@link SearchSuggestion.Section.Item.Url }
     * 
     */
    public SearchSuggestion.Section.Item.Url createSearchSuggestionSectionItemUrl() {
        return new SearchSuggestion.Section.Item.Url();
    }

    /**
     * Create an instance of {@link SearchSuggestion.Section.Item }
     * 
     */
    public SearchSuggestion.Section.Item createSearchSuggestionSectionItem() {
        return new SearchSuggestion.Section.Item();
    }

}
