//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.30 at 11:14:26 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://opensearch.org/searchsuggest2", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package dk.kea.si.movies.domain.wiki;
